### ISSUE TITLE
commented code in User contributed notes can overflow

### ISSUE THREAD

**Issue by Erol314** [php/web-php#769] opened 2023-04-07 08:33 UTC
Not sure if this is the right place to make the issue*

I suppose this is applied to all comments, but this example comes to my eyes. 
https://www.php.net/manual/en/function.unpack.php#110102 

Browser: any

**Comment by kamil-tekiela** [comment] 2023-04-11 13:03
Duplicate of #768 Thanks for reporting though.

**Closed by kamil-tekiela** 2023-04-11 13:03 UTC
