### ISSUE TITLE
The manual is now missing function version info.

### ISSUE THREAD

**Issue by sy-records** [php/web-php#818] opened 2023-10-30 06:48 UTC
before:

<img width="587" alt="image" src="https://github.com/php/web-php/assets/33931153/6644832e-a99d-45d8-a2da-620ca79d6437">

now: 

<img width="559" alt="image" src="https://github.com/php/web-php/assets/33931153/c42df77b-b19e-4d5f-bcfe-c78fce8696cb">

---

### Related links

https://github.com/php/phd/pull/85
https://github.com/php/doc-en/pull/2881

**Comment by TimWolla** [comment] 2023-10-31 13:31
Duplicate of php/doc-en#2892

**Closed** 2023-11-01 12:42 UTC
