### ISSUE TITLE
Recursion in the Russian version of the documentation.

### ISSUE THREAD

**Issue by ShurinokOleksandr** [php/web-php#1192] opened 2024-12-26 06:18 UTC
![Screenshot_3](https://github.com/user-attachments/assets/cf60f7b2-e3de-4f98-a078-df5b0063f0d2)

**Comment by sy-records** [comment] 2024-12-26 06:24
Thank you for your feedback.

Duplicate of #1122

**Closed by sy-records** 2024-12-26 06:24 UTC

**Comment by ShurinokOleksandr** [comment] 2024-12-26 06:44
Thanks for the answer , but did you manage to solve anything? :)

**Comment by ShurinokOleksandr** [comment] 2024-12-26 06:45
> [sy-records](/sy-records)



> Thank you for your feedback.
> 
> Duplicate of #1122
Thanks for the answer , but did you manage to solve anything? :)
