### ISSUE TITLE
Code examples no longer copy properly when using Firefox

### ISSUE THREAD

**Issue by wrossmann** [php/web-php#738] opened 2022-12-12 19:25 UTC
Firefox has recently released a "bugfix" that causes it to copy `&nbsp;` as a unicode non-breaking space `\xC2\xA0`.

All code examples in the manual appear to use `&nbsp;` rather than a plain `\x20`.

The net effect is that anyone using Firefox to browse the manual, and a text editor that does not automatically convert or highlight non-breaking spaces, winds up with broken code and puzzling error messages like 'Parse error: syntax error, unexpected identifier " "'. I have been seeing a number of questions about this crop up on StackOverflow and IRC over the last few weeks, but I wouldn't have guessed that this was the source.

Tested in Firefox 107. Edge and Chrome do not seem to be affected by this.

**Comment by kamil-tekiela** [comment] 2022-12-12 19:47
Both VS Code and PHP Storm display the invisible spaces correctly. I'd expect most IDEs to somehow show these or offer a way to convert them into normal spaces. 

But I also agree that the use of nbsp on php.net is not correct. I think we should change it. I guess this will require a simultaneous PR to both web-php and phd.

**Comment by kamil-tekiela** [comment] 2022-12-12 20:15
Actually, the PHP code examples are created by `highlight_string()` which means that this isn't so easy to fix.

**Comment by wrossmann** [comment] 2022-12-12 20:24
Oof.

I suppose a third `$options` argument could be added with a flag for `DISABLE_NONBREAKING_SPACES` or somesuch, but that's a whole PR and release cycle. `:/`

**Comment by cmb69** [comment] 2022-12-13 12:12
Is this really about the examples on the new minor releases, such as https://www.php.net/releases/8.2/en.php, or is it about examples in the manual proper, e.g. https://www.php.net/manual/en/function.array.php#refsect1-function.array-examples. If the latter, this would be a duplicate of https://github.com/php/phd/issues/71.

**Closed** 2022-12-13 19:57 UTC
